### ISSUE TITLE
PHP Developer Roadmap 

### ISSUE THREAD

**Issue by Lyletimotheus** [Lyletimotheus/Back-end-Development#1]
### How Internet & Websites works

- [x] How does the INTERNET work? (https://youtu.be/x3c1ih2NJEg)
- [x] How The Web Works - The Big Picture (https://youtu.be/hJHvdBlSxug)
- [x] How does the internet work? (Full Course) (https://youtu.be/zN8YNNHcaZc)

### Browser/Server request flow, HTTP Protocol, Status codes

- [x] HTTP Crash Course & Exploration (https://youtu.be/iYM2zFP3Zn0)
- [x] MDN HTTP Tutorial (https://developer.mozilla.org/en-US/docs/Web/HTTP)
- [x] Wikipedia Status Codes (https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)

### Basics of HTML/CSS

- [x] HTML Tutorial for Beginners (https://youtu.be/qz0aGYrrlhU)
- [x] HTML Crash Course For Absolute Beginners (https://youtu.be/UB1O30fR-EE)
- [x] HTML Full Course - Build a Website Tutorial (https://youtu.be/pQN-pnXPaVg)
- [x] CSS Crash Course For Absolute Beginners (https://youtu.be/yfoY53QXEnI)
- [x] CSS Tutorial - Zero to Hero (Complete Course) (https://youtu.be/1Rs2ND1ryYc)

### Basics of JavaScript

- [x] Javascript Crash Course for beginners (https://youtu.be/hdI2bqOjy3c)
- [ ] Learn JavaScript - Full Course for Beginners (https://youtu.be/PkZNo7MFNFg)

### Introduction to Databases

- [ ] MySQL Tutorial for Beginners [Full Course] (https://youtu.be/7S_tz1z_5bA)
- [ ] SQL Tutorial - Full Database Course for Beginners (https://youtu.be/HXV3zeQKqGY)\
- [ ] PHP MySql Tutorial (https://www.mysqltutorial.org/php-mysql/)
- [ ] PHP MySql Tutorial (https://www.w3schools.com/php/php_mysql_intro.asp)

### Version Control System (Git & Github)

- [ ] Git & Github Tutorial for Absolute Beginners (https://youtu.be/iCKAWxfVWUY)
- [ ] Git & GitHub Crash Course For Beginners (https://youtu.be/SWYqp7iY_Tc)

### Getting Familiar with PHP: Syntax, functions, dates, JSON, File System, CURL, etc...

- [ ] PHP Tutorial for Absolute Beginners - PHP Course 2021 (https://youtu.be/yXzWfZ4N4xU)
- [ ] Learn PHP The Right Way - Full PHP Tutorial For Beginners & Advanced (https://www.youtube.com/playlist?list=PLr3d3QYzkw2xabQRUpcZ_IBk9W50M9pe-)

### Understanding Composer
####This section is in under development

### PHP beginner projects

- [ ] Simple CRUD application with PHP and JSON (https://youtu.be/DWHZSkn5paQ)
- [ ] Todo app with PHP (https://youtu.be/NxeNqHdJFxs)
- [ ] PHP Watch files and directories recursively (PHP Watch files and directories recursively) (https://youtu.be/5f4PjQJI-Fc)
- [ ] Bulk image resize with PHP (https://youtu.be/Z99lYtn3quk)
- [ ] PHP registration form & validation (https://youtu.be/V5sJ76T3mWg)

### Object Oriented PHP

- [ ] Object-oriented Programming in 7 minutes (https://youtu.be/pTB0EiLXUC8)
- [ ] Object Oriented PHP For beginners (https://www.youtube.com/watch?v=JmDHHhxfe1w&list=PLLQuc_7jk__VDhXWi544iK-SgljlGGlrX)
- [ ] Object Oriented PHP Tutorials (https://www.youtube.com/watch?v=Anz0ArcQ5kI&list=PL0eyrZgxdwhypQiZnYXM7z7-OTkcMgGPh)
- [ ] Object Oriented PHP Tutorial (https://www.youtube.com/watch?v=LuWxwLk8StM&list=PL4cUxeGkcC9hNpT-yVAYxNWOmxjxL51Hy)

### Build Projects

- [ ] Build PHP Form Widget using OOP Abstraction (https://youtu.be/sBP6HKRW0sM)
- [ ] Build Shopping Cart with OOP (https://youtu.be/1Ip7_hdSqzY)
- [ ] Create MySql Notes App (https://youtu.be/DOsuFRnBqLU)
- [ ] How To Create A Login System In PHP For Beginners (https://youtu.be/gCo6JqGMi30)

### Postman Tutorials 
- [ ] Postman Beginner's Course (https://www.youtube.com/watch?v=VywxIQ2ZXw4)

### Build custom MVC Framework

- [ ] Build PHP MVC Framework (https://www.youtube.com/watch?v=WKy-N0q3WRo&list=PLLQuc_7jk__Uk_QnJMPndbdKECcTEwTA1)

### What is API

- [ ] What is an API? (https://youtu.be/s7wmiS2mSXY)
- [ ] APIs for Beginners - How to use an API (Full Course / Tutorial) (https://youtu.be/GZvSYJDk-us)
- [ ] Build PHP REST API From Scratch (https://www.youtube.com/watch?v=OEWXbpUMODk&list=PLillGF-RfqbZ3_Xr8do7Q2R752xYrDRAo)

### Learn Existing Framework

- [ ] Laravel PHP Framework Tutorial - Full Course for Beginners (https://youtu.be/ImtZ5yENzgE)
- [ ] Laravel PHP Framework Tutorial - Full Course (2020) (https://youtu.be/BXiHvgrJfkg)
- [ ] Yii2 PHP Framework - Full Course (Build a YouTube Clone) (https://youtu.be/whuIf33v2Ug)
- [ ] Symfony PHP Framework Tutorial - Full Course (https://youtu.be/Bo0guUbL5uo)
- [ ] Yii2 Framework course playlist (https://www.youtube.com/watch?v=JD5Y-lQNrPs&list=PLLQuc_7jk__V3jQ0Xr4Rho2lSDztspOt9)

### Learn Javascript

- [ ] Object Oriented JavaScript (https://youtu.be/PFmuCDHHpwk)
- [ ] JavaScript DOM Course (https://www.youtube.com/watch?v=0ik6X4DJKCc&list=PLillGF-RfqbYE6Ik_EuXA2iZFcE082B3s)
- [ ] Asynchronouse JavaScript (https://youtu.be/_8gHHBlbziw)

### Basics of JavaScript Frameworks

- [ ] Angular Crash Course (https://youtu.be/Fdf5aTYRW0E)
- [ ] React Crash Course (https://youtu.be/w7ejDZ8SWv8)
- [ ] Vue Crash Course (https://youtu.be/qZXt1Aom3Cs)
- [ ] Vue3 Crash Course (https://youtu.be/ZqgiuPt5QZo)

#### Yii2 Framework

- [ ] Yii2 E-commerce website - Full Working Process (https://youtu.be/eQdDBhQpU9o)
- [ ] Build a REST API using Yii2 PHP Framework (https://youtu.be/XyHHMvRt6Cw)
- [ ] Vue.js & Yii2 REST API notes app (https://youtu.be/7vrctmDQYW4)

#### Laravel

- [ ] Laravel E-Commerce (https://www.youtube.com/watch?v=o5PWIuDTgxg&list=PLEhEHUEU3x5oPTli631ZX9cxl6cU_sDaR)
- [ ] Laravel Movie App (https://www.youtube.com/watch?v=9OKbmMqsREc&list=PLEhEHUEU3x5pYTjZze3fhYMB4Nl_WOHI4)

### Get Familiar with Terminal

- [ ] Beginner's Guide To The Linux Terminal (https://youtu.be/s3ii48qYBxA)

### Editors/IDEs

- [ ] Visual Studio Code Tutorial for Beginners (https://youtu.be/VqCgcpAypFQ)
- [ ] Visual Studio Code Crash Course (https://youtu.be/WPqXP_kLzpo)
- [ ] VS Code SuperHero course (https://vscodehero.com/)
- [ ] Top 12 VScode Extensions for PHP (https://youtu.be/v9dWFbiir9Q)
- [ ] Introduction to PHPStorm (https://youtu.be/pP9jw3fgrCU)
- [ ] PHPStorm vs VSCode for PHP Development (https://youtu.be/O9nIE-40uKk)
- [ ] Be Awesome in PHPStorm (Laracasts) (https://laracasts.com/series/how-to-be-awesome-in-phpstorm)

### Docker 

- [ ] Docker Tutorial for Beginners (https://youtu.be/3c-iBn73dDE)
- [ ] Docker Tutorial for Beginners - A Full DevOps Course on How to Run Applications in Containers (https://youtu.be/fqMOX6JJhGo)
- [ ] How to Create PHP Development Environments with Docker Compose (https://youtu.be/l0jb-N5H52A)

### Design Patterns

- [ ] Design Patterns in Plain English (https://youtu.be/NU_1StN5Tkk)
- [ ] 5 Design Patterns Every Engineer Should Know (https://youtu.be/FLmBqI3IKMAo)
